production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  vkontakte_app_id: <%= ENV["vkontakte_app_id"] %>
  vkontakte_app_secret: <%= ENV["vkontakte_app_secret"] %>
  twitter_app_id: <%= ENV["twitter_app_id"] %>
  twitter_app_secret: <%= ENV["twitter_app_secret"] %>
